version: "3"

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - "5000:5000"
    environment:
      PORT: 5000
      MODEL: "llama3.2:1b"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
